"use client";

import { Inter } from "next/font/google";
import { Container } from "@mui/material";
import { createContext, useEffect, useState } from "react";

export const ContextApi = createContext({});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    //company data STATE
    const [companyData, setCompanyData] = useState({
      projectName: "",
      projectDescription: "",
      client: "",
      contractor: "",
      max_X: "",
      max_Y: "",
      max_Z: "",
      min_X: "",
      min_Y: "",
      min_Z: "",
    });


  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextApi.Provider value={{companyData,setCompanyData}}>
        {children}
        </ContextApi.Provider>
      </body>
    </html>
  );
}
